version: '3.7'

services:
  php: &php
    build:
      context: .
      dockerfile: .docker/dev/php/Dockerfile
    working_dir: /app
    volumes:
      - .:/app

  composer:
    <<: *php
    entrypoint: composer
